t={
'start':'Hej. Jestem Bot. Staszek Bot',
'dunno':'yyyyyy... tak',
'error':'Stało się coś bardzo złego...',
'nogroup':'Jesteśmy tu sami...',
'notallowed':'To nie jest miejsce na takie rozmowy.',
'freeroll':'Rzut na koszt firmy.',
'countdown':'Rzut dostępny za ',
'nomana':'To zbyt kosztowny czar jest',
'restart':'Idę w kierunku światła...',
'addstickerst1':'Dawaj stickera',
'addstickerst2':'Teraz kategorię',
'addstickerst3':'Nowy sticker już w bazie',
'notfriend':'Aż tak dobrze to się nie znamy',
'friendone':'Ok, znamy się tylko z jednej grupy',
'choosegroup':'Wybierz grupę dla tego zdjęcia',
'photowait':'Ok, dawaj fotkę',
'photospec':'To jednak nie będzie takie proste.',
'specphoto':'Masz zdjęcie na wypadek gdy:',
'chphall':'spyta ktokolwiek',
'chphspec':'spyta ',
'phadded':'fotka dodana, dzięki!',
'ctimeout':'Nie no, tyle czasu to ja nie mam...',
'addanswer':'Dawaj odpowiedź',
'addquestion':'Najpierw pytanie',
'answerok':'Zrobione',
'addrollsterr':'to powinno wyglądac tak: /addrollsticker ALIAS KATEGORIA',
'addrollstok':'poszło'
}
